name: auto_glass_crm
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.8+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_messaging: ^5.0.4
  firebase_storage: ^3.1.1

  material_design_icons_flutter: ^3.0.3392
  shimmer: ^0.0.6
  servicestack: "^1.0.8"
  http: ^0.12.0+4
  shared_preferences: "^0.5.6"
  url_launcher: ^5.0.0
  image_picker: ^0.6.3+1
  #flutter_image_pick_crop: ^0.0.1
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  signature_pad: ^2.1.0+1
  uni_links: ^0.1.4
  string_mask: ^0.1.0
  dio: ^2.1.2
  intl: ^0.15.7
  autocomplete_textfield: ^1.6.4
  datetime_picker_formfield: ^0.4.2
  html_unescape: ^1.0.1+3
  validators: ^2.0.0
  flutter_local_notifications: ^0.9.1+3
  photo_view: ^0.9.0
  youtube_player_flutter: ^6.0.0
  video_thumbnail: ^0.2.0
  path: ^1.6.4
  path_provider: ^1.5.1
  flutter_device_type: ^0.2.0
  multi_image_picker: ^4.6.3

  flutter_camera_ml_vision: ^2.2.4
  camera: ^0.5.7+4
  export_video_frame: ^0.0.5+4
  media_info: ^0.6.1
  video_player: ^0.10.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/logo.jpg
    - assets/logo_sm.png
    - assets/skele.png
    - assets/ic_logo_blue.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
